package cli_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/yersonargotev/dots/internal/backups"
	"github.com/yersonargotev/dots/internal/cli"
	"github.com/yersonargotev/dots/internal/state"
)

func TestBatConfigMigratesToWholeTargetAndPreservesGeneratorDrift(t *testing.T) {
	requireGitCLI(t)
	home := t.TempDir()
	stateRoot := filepath.Join(home, ".dots-state")
	t.Setenv("HOME", t.TempDir())

	baseline := "--theme=\"Catppuccin Mocha\"\n"
	generated := "# Generated by bat\n--plain\n"
	origin, sourceRoot := newInstalledRepo(t, map[string]string{
		"configs/bat/config": baseline,
		"dots.yaml":          batManifest("symlink"),
	})
	manifestPath := filepath.Join(sourceRoot, "dots.yaml")

	run := func(want int, args ...string) string {
		t.Helper()
		var stdout, stderr bytes.Buffer
		code := cli.Run(args, &stdout, &stderr)
		if code != want {
			t.Fatalf("cli.Run(%v) code = %d, want %d\nstdout:\n%s\nstderr:\n%s", args, code, want, stdout.String(), stderr.String())
		}
		return stdout.String()
	}
	common := []string{"--profile", "default", "--file", manifestPath, "--home", home, "--source-root", sourceRoot, "--state-root", stateRoot}
	run(0, append([]string{"install", "--yes", "--skip-deps"}, common...)...)

	target := filepath.Join(home, ".config", "bat", "config")
	if info, err := os.Lstat(target); err != nil || info.Mode()&os.ModeSymlink == 0 {
		t.Fatalf("legacy bat config = (%v, %v), want symlink", info, err)
	}

	advanceUpstream(t, origin, "materialize bat config", map[string]string{"dots.yaml": batManifest("copy")})
	updateOutput := runUpdate(t, "--yes", "--profile", "default", "--file", manifestPath, "--home", home, "--source-root", sourceRoot, "--state-root", stateRoot)
	if !strings.Contains(updateOutput, "migrate") {
		t.Fatalf("update output missing bat migration evidence:\n%s", updateOutput)
	}
	if info, err := os.Lstat(target); err != nil || !info.Mode().IsRegular() {
		t.Fatalf("migrated bat config = (%v, %v), want regular file", info, err)
	}
	if got, err := os.ReadFile(target); err != nil || string(got) != baseline {
		t.Fatalf("migrated bat config = (%q, %v), want baseline", got, err)
	}
	backupMeta, err := backups.Load(backups.Path(stateRoot))
	if err != nil || len(backupMeta.Sets) != 1 {
		t.Fatalf("migration Backup Sets = %#v, err = %v", backupMeta, err)
	}
	preserved, err := os.ReadFile(backups.FilePath(stateRoot, backupMeta.Sets[0].ID, 1, target))
	if err != nil || string(preserved) != baseline {
		t.Fatalf("migration backup = %q, err = %v", preserved, err)
	}

	if err := os.WriteFile(target, []byte(generated), 0o600); err != nil {
		t.Fatalf("simulate bat --generate-config-file: %v", err)
	}
	if dirty := strings.TrimSpace(runGitOutput(t, sourceRoot, "status", "--porcelain")); dirty != "" {
		t.Fatalf("simulated bat generation dirtied the Installed Repository: %q", dirty)
	}
	statusOutput := run(2, append([]string{"status", "--output", "json"}, common...)...)
	if !strings.Contains(statusOutput, `"state": "drifted"`) {
		t.Fatalf("status did not report generated bat config as Drift:\n%s", statusOutput)
	}

	run(0, append([]string{"install", "--yes", "--skip-deps"}, common...)...)
	runUpdate(t, "--yes", "--profile", "default", "--file", manifestPath, "--home", home, "--source-root", sourceRoot, "--state-root", stateRoot)
	if got, err := os.ReadFile(target); err != nil || string(got) != generated {
		t.Fatalf("install/update changed generated bat config = (%q, %v)", got, err)
	}

	uninstallOutput := run(0, "uninstall", "--yes", "--home", home, "--source-root", sourceRoot, "--state-root", stateRoot)
	if !strings.Contains(uninstallOutput, "modified target(s) will be skipped") {
		t.Fatalf("uninstall output missing modified-target evidence:\n%s", uninstallOutput)
	}
	if got, err := os.ReadFile(target); err != nil || string(got) != generated {
		t.Fatalf("uninstall changed generated bat config = (%q, %v)", got, err)
	}
}

func TestBatLegacySymlinkWithoutProvenanceFailsClosed(t *testing.T) {
	requireGitCLI(t)
	home := t.TempDir()
	stateRoot := filepath.Join(home, ".dots-state")
	t.Setenv("HOME", t.TempDir())

	baseline := "--theme=\"Catppuccin Mocha\"\n"
	origin, sourceRoot := newInstalledRepo(t, map[string]string{
		"configs/bat/config": baseline,
		"dots.yaml":          batManifest("symlink"),
	})
	manifestPath := filepath.Join(sourceRoot, "dots.yaml")
	var stdout, stderr bytes.Buffer
	if code := cli.Run([]string{"install", "--yes", "--skip-deps", "--profile", "default", "--file", manifestPath, "--home", home, "--source-root", sourceRoot, "--state-root", stateRoot}, &stdout, &stderr); code != 0 {
		t.Fatalf("legacy install code = %d\nstdout:\n%s\nstderr:\n%s", code, stdout.String(), stderr.String())
	}
	meta, err := state.Load(state.Path(stateRoot))
	if err != nil {
		t.Fatalf("load legacy metadata: %v", err)
	}
	meta.Provenance = state.Provenance{}
	if err := state.Save(state.Path(stateRoot), meta); err != nil {
		t.Fatalf("remove provenance from legacy metadata: %v", err)
	}

	advanceUpstream(t, origin, "materialize bat config", map[string]string{"dots.yaml": batManifest("copy")})
	output := runUpdate(t, "--yes", "--profile", "default", "--file", manifestPath, "--home", home, "--source-root", sourceRoot, "--state-root", stateRoot)
	target := filepath.Join(home, ".config", "bat", "config")
	if !strings.Contains(output, "conflict") {
		t.Fatalf("update output missing unproven migration conflict:\n%s", output)
	}
	if info, err := os.Lstat(target); err != nil || info.Mode()&os.ModeSymlink == 0 {
		t.Fatalf("unproven legacy target = (%v, %v), want preserved symlink", info, err)
	}
	backupMeta, err := backups.Load(backups.Path(stateRoot))
	if err != nil || len(backupMeta.Sets) != 0 {
		t.Fatalf("unproven migration Backup Sets = %#v, err = %v", backupMeta, err)
	}
}

func batManifest(strategy string) string {
	return `version: 1
profiles:
  default:
    tags: [core]
entries:
  - source: configs/bat/config
    target: ~/.config/bat/config
    strategy: ` + strategy + `
    tags: [core]
`
}
